name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        VITE_BASE_URL: /AInewsh5/
        VITE_APP_TITLE: AI新闻推送
        VITE_APP_DESCRIPTION: 国际AI新闻推送H5应用
        VITE_APP_VERSION: 1.0.0
        # API Keys (从GitHub Secrets获取)
        VITE_GNEWS_API_KEY: ${{ secrets.VITE_GNEWS_API_KEY }}
        VITE_NEWS_API_KEY: ${{ secrets.VITE_NEWS_API_KEY }}
        VITE_NEWSDATA_API_KEY: ${{ secrets.VITE_NEWSDATA_API_KEY }}
        VITE_SILICONFLOW_API_KEY: ${{ secrets.VITE_SILICONFLOW_API_KEY }}
        VITE_TENCENT_SECRET_ID: ${{ secrets.VITE_TENCENT_SECRET_ID }}
        VITE_TENCENT_SECRET_KEY: ${{ secrets.VITE_TENCENT_SECRET_KEY }}
        VITE_BAIDU_APP_ID: ${{ secrets.VITE_BAIDU_APP_ID }}
        VITE_BAIDU_SECRET_KEY: ${{ secrets.VITE_BAIDU_SECRET_KEY }}
        VITE_ALIBABA_ACCESS_KEY_ID: ${{ secrets.VITE_ALIBABA_ACCESS_KEY_ID }}
        VITE_ALIBABA_ACCESS_KEY_SECRET: ${{ secrets.VITE_ALIBABA_ACCESS_KEY_SECRET }}
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: /AInewsh5